let handler = async (m, { conn }) => {

    let frases = [
        // 25 ÉPICAS 👑
        'No soy vago, estoy en modo ahorro de energía','Rey no se hace, rey se nace','Calla y mira como trabajo','Los débiles se quejan, los fuertes actúan','Si el plan falla, cambia el plan no la meta','Caer 7 veces, levantarse 8','El dolor es temporal, el orgullo es para siempre','No compito con nadie, yo soy mi competencia','La disciplina gana a la motivación','Si quieres algo, ve y tómalo','El éxito es 1% inspiración y 99% desvelo','No expliques, demuestra','Grandes cosas nunca vinieron de zonas de confort','Sueña en grande, trabaja más grande','Hoy hago lo que otros no, para mañana tener lo que otros no tienen','El que no arriesga no gana','Tu única limitación es la que tú te pones','Trabaja en silencio, deja que el éxito haga ruido','No cuentes los días, haz que los días cuenten','Si no te gusta algo, cámbialo','El futuro depende de lo que hagas hoy','No pares hasta estar orgulloso','Cree en ti y todo será posible','La persistencia vence la resistencia','Hazlo ahora o lamenta después',
        // 25 TROLLS 😈
        'Tu ex me contó todo... y se rió','Si la ignorancia duele, tú vives en UCI','No es que sea malo, es que tu nivel es muy bajo','Eres como WiFi, me conecto cuando quiero','Hablo poco porque copio poco','Me caes mal pero me caes bien','Tienes cara de me bloquearon del grupo','Si fueras nota serías 0.5','Tu opinión es como tu internet: no sirve','Eres el error 404 de la vida','Si la belleza fuera delito, cadena perpetua','Hablas tanto que hasta el silencio te extraña','Tu cerebro tiene modo avión permanente','Eres como lunes, nadie te quiere','Si fueras aplicación serías publicidad','Tienes menos apoyo que Windows Vista','Tu cara pide perdón por tu personalidad','Eres la razón por la que shampoo trae instrucciones','Si fueras chiste ya te hubieran cancelado','Más perdido que tu ex en responsabilidad afectiva','Tu vida es spoiler de fracaso','Eres como factura, todos te evitan','Si fueras wifi serías sin contraseña y sin señal','Hablas de humildad con cara de iPhone 15','Eres el motivo por el que existe el botón de silenciar',
        // 25 DIVERTIDAS 😂
        'Estoy a dieta... de sueño y de plata','Mi cama y yo tenemos una relación seria','Si me pierdo que me busquen en la refri','Modo zombie activado: no molestar','El que madruga no soy yo','90% agua, 10% café y 100% sueño','Estoy en mis días... lunes, martes, miércoles...','Mi vida es un meme que nadie entiende','Sobreviviendo a base de café y traumas','Hoy no, cerebro. Hoy no','Si el plan A falla, tengo plan B: dormir','Soy como el autoestima, vengo y me voy','Necesito vacaciones de mis vacaciones','Mi talento oculto es desaparecer los lunes','Estoy fino... de no hacer nada','Si ignorar fuera deporte, sería olímpico','Mi banco y yo tenemos una relación tóxica','No tengo tiempo... para hacer tiempo','Vivo en modo ahorro de batería','Si procrastinar fuera arte, sería Picasso','Tengo 2 modos: modo comida y modo sueño','Mi vida social es un contacto de emergencia','Soy experto en empezar el lunes','Si el estrés fuera cardio ya estaría marcado','Me levanto con el pie equivocado y sigo así todo el día',
        // 25 JODIDAS ☠️
        'Más falso que billete de 3 soles','Eres la razón por la que se inventó el modo avión','Si fueras tarea ya te hubiera copiado','Tu cerebro tiene menos gigas que mi Nokia','Habla menos, que el WiFi te escucha','Más liso que pista de patinaje','Eres como el examen, nadie te quiere','Tu foto de perfil da risa sin querer','Si fueras nota musical serías silencio','Tienes cara de me deben 5 soles','Eres más inútil que letra chiquita','Si fueras app serías la que nadie actualiza','Más vacío que promesa de político','Tu personalidad es como tu internet: intermitente','Eres como recibo de luz, llega sin avisar','Si fueras consejo sería no sigas este consejo','Tienes menos chispa que foco ahorrador','Eres el lag de la vida real','Más frío que ex después de ghostear','Si fueras nota de voz durarías 10 minutos','Eres como spam, nadie te pidió','Tu vida es tutorial de como no hacer las cosas','Más tieso que saludo de suegra','Si fueras meme ya estarías desactualizado','Eres la actualización que nadie quería',
        // 20 +18 🔥
        'Mi cama no me suelta y yo no la suelto a ella','Solo vengo a ver el chisme y a robarme a alguien','Advertencia: puedo ponerme intenso después de las 12','Si me miras así me voy a ilusionar oe','Tengo cara de inocente pero mente de diablo','No busco nada serio... solo risas y algo más','Me gustas, pero me da flojera enamorarme','Soy el problema y la solución a la vez','Cuidado que muerdo... pero rico','Mi humor es negro y mi corazón peor','Busco culpable para mis malas decisiones: yo','Si me das confianza me malcrió','Tengo novio/a... se llama Sueño','No soy celoso, solo territorial','Mi tipo: el que me responda los mensajes','Advertencia: contenido no apto para santos','Si me provocas, me aguantas','Estoy soltero... pero ocupado ligando','No prometo nada, pero tampoco descarto nada','Modo diablo: activado'
    ]

    let frase = frases[Math.floor(Math.random() * frases.length)]
    m.reply(`*📜 FRASE RANDOM* 📜\n\n"${frase}"`)
}

handler.command = ['frase']
export default handler